# no logging
CONFIG_ZMK_USB_LOGGING=n

# no USB
#CONFIG_ZMK_USB=n

# conf BLE
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
CONFIG_BT_MAX_PAIRED=4
CONFIG_BT_MAX_PAIRED=5
CONFIG_BT_BAS=y

# improve the BLE with experimental features
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# fetch the periph battery level to the host
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# enable deep sleep support
CONFIG_ZMK_SLEEP=y

# the keyboard disconnects from bluetooth.
# uses very little power, but it may take
# a few seconds to reconnect after waking.
# 1.800.000 ms = 30 minutes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# enable soft off behavior
# https://zmk.dev/docs/config/power#soft-off
CONFIG_ZMK_PM_SOFT_OFF=y
